version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yea1
      - MYSQL_DB=user_registration
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yea1
      MYSQL_DATABASE: user_registration
      MYSQL_USER: root
      MYSQL_PASSWORD: yea1
    ports:
      - "3306:3306"
